<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Version>1.0.8</Version>
    <Product>GIBS.Module.Entity</Product>
    <Authors>GIBS</Authors>
    <Company>GIBS</Company>
    <Description>User defined entity definitions, grouped fields, typed values, searchable, filterable metadata, and entity specific templates.</Description>
    <Copyright>GIBS</Copyright>
    <AssemblyName>GIBS.Module.Entity.Server.Oqtane</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <StaticWebAssetsFingerprintContent>false</StaticWebAssetsFingerprintContent>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\_content\**\*.*" />
    <None Include="wwwroot\_content\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\GIBS.Module.Entity.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Oqtane.Server"><HintPath>..\..\oqtane.framework\Oqtane.Server\bin\Debug\net10.0\Oqtane.Server.dll</HintPath></Reference>
    <Reference Include="Oqtane.Shared"><HintPath>..\..\oqtane.framework\Oqtane.Server\bin\Debug\net10.0\Oqtane.Shared.dll</HintPath></Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Configuration\" />
    <Folder Include="Services\Extensions\" />
    <Folder Include="Services\Implementation\" />
  </ItemGroup>
</Project>
