//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBS.Module.Entity.Client.Resources.GIBS_Module_Entity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BackOffice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackOffice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIBS.Module.Entity.Client.Resources.GIBS.Module.Entity.BackOffice", typeof(BackOffice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Management.
        /// </summary>
        internal static string BackOffice_Description {
            get {
                return ResourceManager.GetString("BackOffice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackOffice.
        /// </summary>
        internal static string BackOffice_Title {
            get {
                return ResourceManager.GetString("BackOffice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string BackToEntities {
            get {
                return ResourceManager.GetString("BackToEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Record Description.
        /// </summary>
        internal static string EntityRecordDescription {
            get {
                return ResourceManager.GetString("EntityRecordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Records.
        /// </summary>
        internal static string EntityRecords {
            get {
                return ResourceManager.GetString("EntityRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Types.
        /// </summary>
        internal static string EntityTypes {
            get {
                return ResourceManager.GetString("EntityTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Entity Types.
        /// </summary>
        internal static string EntityTypes_Description {
            get {
                return ResourceManager.GetString("EntityTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Types.
        /// </summary>
        internal static string EntityTypes_Title {
            get {
                return ResourceManager.GetString("EntityTypes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Groups.
        /// </summary>
        internal static string FieldGroups {
            get {
                return ResourceManager.GetString("FieldGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Field Groups.
        /// </summary>
        internal static string FieldGroupsDescription {
            get {
                return ResourceManager.GetString("FieldGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Fields.
        /// </summary>
        internal static string Fields_Description {
            get {
                return ResourceManager.GetString("Fields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string Fields_Title {
            get {
                return ResourceManager.GetString("Fields_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Entity Type to Manage:.
        /// </summary>
        internal static string SelectEntityType {
            get {
                return ResourceManager.GetString("SelectEntityType", resourceCulture);
            }
        }
    }
}
